Entity/Nodo.php
<?php 
namespace SUR\SecurityBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Nodo
 *
 * @ORM\Table(name="nodo")
 * @ORM\Entity
 */
class Nodo{
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="nodo_id", type="integer", nullable=false)
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $nodo_id;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="nodo_nombre", type="string", length=100, nullable=false)
	 */
	private $nodo_nombre;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="nodo_archivo", type="string", length=100, nullable=false)
	 */
	private $nodo_archivo;
	

	//FIXME Aca van las aristas con sus nodos hijos
	protected $hijos;
	
	public function getNodoId() {
		return $this->nodo_id;
	}
	public function setNodoId($nodo_id) {
		$this->nodo_id = $nodo_id;
		return $this;
	}
	public function getNodoNombre() {
		return $this->nodo_nombre;
	}
	public function setNodoNombre($nodo_nombre) {
		$this->nodo_nombre = $nodo_nombre;
		return $this;
	}
	public function getNodoArchivo() {
		return $this->nodo_archivo;
	}
	public function setNodoArchivo($nodo_archivo) {
		$this->nodo_archivo = $nodo_archivo;
		return $this;
	}
	public function getHijos(){
		return $this->hijos;
	}
	public function addHijo($nodo){
		$this->hijos[] = $nodo;
	}
	
}

Controller/DefaultController.php
<?php

namespace SUR\SecurityBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use SUR\SecurityBundle\Entity\Nodo;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class DefaultController extends Controller
{
    /**
     * @Template()
     */
    public function menuAction()
    {
//     	$nodoDAO = $this->getDoctrine()->getRepository('SURSecurityBundle:Nodo');
//     	$menu = $nodoDAO->findHeaders(); //FIXME Recuperar el Id de Usuario logueado
    
    	$menu = $this->buildMockMenu();
    	
    	return array('menu' => $menu);
    }
    
    private function buildMockMenu(){
    	$m1 = new Nodo();
    	$m1->setNodoArchivo("#");
    	$m1->setNodoNombre("Menu 1");
	    	$m11 = new Nodo();
	    	$m11->setNodoArchivo("acme_hello_projects");
	    	$m11->setNodoNombre("Menu 1.1");
	    	$m1->addHijo($m11);
	    	$m12 = new Nodo();
	    	$m12->setNodoArchivo("acme_hello_projects_add");
	    	$m12->setNodoNombre("Menu 1.2");
	    	$m1->addHijo($m12);
	    	
    	$m2 = new Nodo();
    	$m2->setNodoArchivo("#");
    	$m2->setNodoNombre("Menu 2");
	    	$m21 = new Nodo();
	    	$m21->setNodoArchivo("acme_hello_employees");
	    	$m21->setNodoNombre("Menu 2.1");
	    	$m2->addHijo($m21);
	    	
	    return array($m1, $m2);
    }
}

Controller/SecuredController.php
<?php

namespace SUR\SecurityBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;

class SecuredController extends Controller
{
    /**
     * @Route("/logout", name="_logout")
     */
    public function logoutAction()
    {
        // The security layer will intercept this request
    }
    
    /**
     * @Route("/login", name="_login")
     */
    public function surAction()
    {
        // The security layer will intercept this request
//     	$this->getRequest()->getSession()->clear();
//     	$this->getRequest()->getSession()->invalidate();
    	return new Response('', 302, array("Location" =>  $this->container->getParameter('login_url')));
    }
}

Tests/Controller/DefaultControllerTest.php
<?php

namespace SUR\SecurityBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
    }
}

Resources/views/Default/index.html.twig
{% extends "AcmeDemoBundle::layout.html.twig" %}
{% block body %}
	<h1>Pagina de Inicio</h1><br />
	<a href="{{ path('_logout') }}">Salir</a>
{% endblock %} 

Resources/views/Default/menu.html.twig
{% spaceless %}
<div id="cssmenu">
	<ul id="jMenu">
		{% for h in menu %}
			<li class='has-sub'>
				<a href="{{ (h.nodoArchivo!= '#') ? path(h.nodoArchivo) : h.nodoArchivo }}" class="fNiv">{{ h.nodoNombre }}</a>
				{% if h.hijos | default() %}
					<ul>
						{{ _self.r(h.hijos)}}
						{% macro r(m) %}
						    {% for s in m %}
						        <li class='has-sub'>
						            <a href="{{ (s.nodoArchivo != '#') ? path(s.nodoArchivo) : s.nodoArchivo }}">{{ s.nodoNombre }}</a>
									{% if s.hijos | default() %}
						                <ul>
						                    {{ _self.r(s.hijos) }}
						                </ul>
						            {% endif %}
						        </li>
						    {% endfor %}
						{% endmacro %}
					</ul>
				{% endif %}
			</li>
		{% endfor %}
	</ul>
</div>
{% endspaceless %}


<!-- 
<div id='cssmenu'>
<ul>
   <li class='active'><a href='index.html'><span>Home</span></a></li>
   <li class='has-sub'><a href='#'><span>Products</span></a>
      <ul>
         <li class='has-sub'><a href='#'><span>Product 1</span></a>
            <ul>
               <li><a href='#'><span>Sub Item</span></a></li>
               <li class='last'><a href='#'><span>Sub Item</span></a></li>
            </ul>
         </li>
         <li class='has-sub'><a href='#'><span>Product 2</span></a>
            <ul>
               <li><a href='#'><span>Sub Item</span></a></li>
               <li class='last'><a href='#'><span>Sub Item</span></a></li>
            </ul>
         </li>
      </ul>
   </li>
   <li><a href='#'><span>About</span></a></li>
   <li class='last'><a href='#'><span>Contact</span></a></li>
</ul>
</div>
 -->

Resources/views/Menu/knp_menu.html.twig
{% extends 'knp_menu.html.twig' %}

{% block item %}
{% import "knp_menu.html.twig" as macros %}
{% if item.displayed %}
    {%- set attributes = item.attributes %}
    {%- set is_dropdown = attributes.dropdown|default(false) %}
    {%- set divider_prepend = attributes.divider_prepend|default(false) %}
    {%- set divider_append = attributes.divider_append|default(false) %}

{# unset bootstrap specific attributes #}
    {%- set attributes = attributes|merge({'dropdown': null, 'divider_prepend': null, 'divider_append': null }) %}

    {%- if divider_prepend %}
        {{ block('dividerElement') }}
    {%- endif %}

{# building the class of the item #}
    {%- set classes = item.attribute('class') is not empty ? [item.attribute('class')] : [] %}
    {%- if matcher.isCurrent(item) %}
        {%- set classes = classes|merge([options.currentClass]) %}
    {%- elseif matcher.isAncestor(item, options.depth) %}
        {%- set classes = classes|merge([options.ancestorClass]) %}
    {%- endif %}
    {%- if item.actsLikeFirst %}
        {%- set classes = classes|merge([options.firstClass]) %}
    {%- endif %}
    {%- if item.actsLikeLast %}
        {%- set classes = classes|merge([options.lastClass]) %}
    {%- endif %}

{# building the class of the children #}
    {%- set childrenClasses = item.childrenAttribute('class') is not empty ? [item.childrenAttribute('class')] : [] %}
    {%- set childrenClasses = childrenClasses|merge(['menu_level_' ~ item.level]) %}

{# adding classes for dropdown #}
    {%- if is_dropdown %}
        {%- set classes = classes|merge(['dropdown']) %}
        {%- set childrenClasses = childrenClasses|merge(['dropdown-menu']) %}
    {%- endif %}

{# putting classes together #}
    {%- if classes is not empty %}
        {%- set attributes = attributes|merge({'class': classes|join(' ')}) %}
    {%- endif %}
    {%- set listAttributes = item.childrenAttributes|merge({'class': childrenClasses|join(' ') }) %}

{# displaying the item #}
    <li{{ macros.attributes(attributes) }}>
        {%- if is_dropdown %}
            {{ block('dropdownElement') }}
        {%- elseif item.uri is not empty and (not item.current or options.currentAsLink) %}
            {{ block('linkElement') }}
        {%- else %}
            {{ block('spanElement') }}
        {%- endif %}
{# render the list of children#}
        {{ block('list') }}
    </li>

    {%- if divider_append %}
        {{ block('dividerElement') }}
    {%- endif %}
{% endif %}
{% endblock %}

{% block dividerElement %}
{% if item.level == 1 %}
    <li class="divider-vertical"></li>
{% else %}
    <li class="divider"></li>
{% endif %}
{% endblock %}

{% block linkElement %}
	<a href="{{ item.uri }}"{{ macros.attributes(item.linkAttributes) }}>
		{% if item.attribute('icon') is not empty  %}
    		<i class="{{ item.attribute('icon') }}"></i> 
    	{% endif %}
		{{ block('label') }}
	</a>
{% endblock %}

{% block spanElement %}
	<span>{{ macros.attributes(item.labelAttributes) }}>
		{% if item.attribute('icon') is not empty  %}
    		<i class="{{ item.attribute('icon') }}"></i> 
    	{% endif %}
		{{ block('label') }}
	</span>
{% endblock %}

{% block dropdownElement %}
    {%- set classes = item.linkAttribute('class') is not empty ? [item.linkAttribute('class')] : [] %}
    {%- set classes = classes|merge(['dropdown-toggle']) %}
    {%- set attributes = item.linkAttributes %}
    {%- set attributes = attributes|merge({'class': classes|join(' ')}) %}
    {%- set attributes = attributes|merge({'data-toggle': 'dropdown'}) %}
    <a href="#"{{ macros.attributes(attributes) }}>
    	{% if item.attribute('icon') is not empty  %}
    		<i class="{{ item.attribute('icon') }}"></i> 
    	{% endif %}
    	{{ block('label') }} 
    	<b class="caret"></b>
    </a>
{% endblock %}

{% block label %}{{ item.label|trans }}{% endblock %}

Resources/views/layout.html.twig
{% block all %}
<!doctype html>
  <html>
  {% block head_outer %}
    <head {{bp_head_attributes|default('')|raw}}>
      {% block head %}
        {% block head_meta %}
{#           <meta charset="utf-8">#}
{#         <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">#}
		  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
          <meta name="description" content="{% block head_meta_description %}{% endblock %}">
          <meta name="keywords" content="{% block head_meta_keywords %}{% endblock %}">
          <meta name="viewport" content="width=device-width">
        {% endblock head_meta %}

        <title>{% block head_title %}{% endblock %}</title>

        {% block head_css %}
		<link rel="stylesheet" href="{{ asset('bundles/sursecurity/css/menu.css') }}">
    	<style type="text/css">
    		#cssmenu span {
				/*border: 1px solid transparent;
				 width: 144px;
				padding: 3px 10px;*/
				display: block;
				color: #666666;
				line-height: 160%;
				padding: 11px 28px 11px 28px;
			}
			#page{
				width: 1000px;
				margin: 0px auto;
			}
			#container{
				padding: 10px;
				/*display: inline-block;*/
				min-width: 780px;
				max-width: 1000px;
				min-height: 200px;
				margin: 0px auto;
			}
    	</style>
        {% endblock %}

        {% block head_js %}

        {% endblock %}
      {% endblock head %}
    </head>
  {% endblock head_outer %}
  {% block body_outer %}
    <body>
      {%block body%}
        {%block body_container%}
          <div id="container">
            <header>
              {% block body_container_header %}
	              {% block menu %}
		            <div id="cssmenu">
					{{ knp_menu_render('SURSecurityBundle:Builder:mainMenu') }}
					</div>
	              {% endblock %}
              {% endblock %}
            </header>
            <div role="main">
              {% block body_container_main %}{% endblock %}
            </div>
            <footer>
              {% block body_container_footer %}{% endblock %}
            </footer>
          </div>
        {%endblock body_container%}
        {% block body_js %}

        {% endblock body_js %}
      {% endblock body %}
    </body>
  {% endblock body_outer %}
</html>{% endblock all %}